# This is a dummy package used to maintain version pins for Plone.
# It must never be released: there is no point to that.
[build-system]
# possibly add mxdev in here, pip-tools, wheel, whatever we want.
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "plonecoredevdummy"
version = "6.0"
description = "Dummy package to help Plone 6 core development"
requires-python = ">=3.8"
dependencies = [
  "Plone~=6.0.0",
]

[project.optional-dependencies]
test = []
tools = []
buildout = []

[tool.setuptools]
# This is a dummy package without code.
packages = []
