# This is a dummy package used to maintain version pins for     "Plone.",
# It must never be released: there is no point to that.
[build-system]
# possibly add mxdev in here, pip-tools, wheel, whatever we want.
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "plonecoredevdummy"
version = "6.0"
description = "Dummy package to help Plone 6 core development"
requires-python = ">=3.8"
# Within a Plone minor release we prefer to only have bugfix releases.
# With "package~=1.2.3" we say: at least 1.2.3, but less thatn 1.3.0.
# See https://peps.python.org/pep-0440/#compatible-release
dependencies = [
    "borg.localrole~=3.1.9",
    "five.customerize~=2.1.0",
    "five.intid~=1.2.6",
    "Plone~=6.0.1",
    "plone.alterego~=1.1.5",
    "plone.api~=2.0.1",
    "plone.app.caching~=3.0.2",
    "plone.app.content~=4.0.1",
    "plone.app.contentlisting~=3.0.1",
    "plone.app.contentmenu~=3.0.0",
    "plone.app.contentrules~=5.0.0",
    "plone.app.contenttypes~=3.0.1",
    "plone.app.customerize~=1.3.12",
    "plone.app.dexterity~=3.0.4",
    "plone.app.discussion~=4.0.0",
    "plone.app.event~=4.0.0",
    "plone.app.i18n~=4.0.0",
    "plone.app.intid~=1.1.4",
    "plone.app.iterate~=4.0.3",
    "plone.app.layout~=4.0.0",
    "plone.app.linkintegrity~=3.6.1",
    "plone.app.locales~=6.0.10",
    "plone.app.lockingbehavior~=1.0.7",
    "plone.app.multilingual~=6.0.0",
    "plone.app.portlets~=5.0.1",
    "plone.app.querystring~=2.0.1",
    "plone.app.redirector~=3.0.0",
    "plone.app.registry~=2.0.1",
    "plone.app.relationfield~=3.0.1",
    "plone.app.textfield~=1.3.7",
    "plone.app.theming~=5.0.0",
    "plone.app.upgrade~=3.0.1",
    "plone.app.users~=3.0.0",
    "plone.app.uuid~=2.2.1",
    "plone.app.versioningbehavior~=2.0.0",
    "plone.app.viewletmanager~=4.0.0",
    "plone.app.vocabularies~=5.0.0",
    "plone.app.widgets~=4.0.0",
    "plone.app.workflow~=5.0.1",
    "plone.app.z3cform~=4.0.1",
    "plone.autoform~=2.0.0",
    "plone.autoinclude~=1.0.1",
    "plone.base~=1.0.3",
    "plone.batching~=2.0.2",
    "plone.behavior~=1.4.0",
    "plone.browserlayer~=3.0.0",
    "plone.cachepurging~=3.0.0",
    "plone.caching~=1.2.2",
    "plone.contentrules~=2.1.2",
    "plone.dexterity~=3.0.1",
    "plone.event~=1.4.2",
    "plone.folder~=3.1.0",
    "plone.formwidget.namedfile~=3.0.0",
    "plone.formwidget.recurrence~=3.0.0",
    "plone.i18n~=5.0.0",
    "plone.indexer~=1.0.7",
    "plone.intelligenttext~=3.1.0",
    "plone.keyring~=3.2.0",
    "plone.locking~=2.3.0",
    "plone.memoize~=3.0.0",
    "plone.namedfile~=6.0.0",
    "plone.outputfilters~=5.0.0",
    "plone.portlet.collection~=4.0.0",
    "plone.portlet.static~=4.0.0",
    "plone.portlets~=2.3.2",
    "plone.protect~=4.1.8",
    "plone.registry~=1.2.1",
    "plone.resource~=2.1.4",
    "plone.resourceeditor~=3.0.4",
    "plone.rest~=3.0.0",
    "plone.restapi~=8.34.0",
    "plone.rfc822~=2.0.2",
    "plone.scale~=4.0.0",
    "plone.schema~=1.4.0",
    "plone.schemaeditor~=4.0.2",
    "plone.session~=4.0.2",
    "plone.staticresources~=2.0.4",
    "plone.stringinterp~=1.3.3",
    "plone.subrequest~=2.0.2",
    "plone.supermodel~=2.0.2",
    "plone.theme~=3.0.7",
    "plone.transformchain~=2.0.2",
    "plone.uuid~=1.0.6",
    "plone.volto~=4.0.5",
    "plone.z3cform~=2.0.0",
    "plonetheme.barceloneta~=3.0.0",
    "Products.CMFDiffTool~=3.3.3",
    "Products.CMFDynamicViewFTI~=7.0.0",
    "Products.CMFEditions~=4.0.0",
    "Products.CMFPlacefulWorkflow~=3.0.2",
    "Products.CMFPlone~=6.0.1",
    "Products.ExtendedPathIndex~=4.0.1",
    "Products.isurlinportal~=1.2.1",
    "Products.MimetypesRegistry~=2.1.9",
    "Products.PlonePAS~=7.0.0",
    "Products.PortalTransforms~=3.2.2",
    "Products.statusmessages~=5.0.5",
]

[project.optional-dependencies]
test = []
tools = []
buildout = []

[tool.setuptools]
# This is a dummy package without code.
packages = []
