# Run: PROJECT_CONFIG=plips/plip-recyclebin.ini make install

[settings]
include = ../mx.ini

[plone.base]
use = true
branch = plip-recyclebin-interface

[plone.app.content]
use = true
branch = rohnsha0/recyclebin-delete-msg


[plone.restapi]
use = true
branch = rohnsha0-feat-recyclebin-api

[Products.CMFPlone]
use = true
branch = rohnsha0-plip-recyclebin-patch

# Soft-delete of comments.
# This is thematically related, but a separate feature.
#[plone.app.discussion]
#use = true
#branch = rohnsha0/enhance-deletion-logic
