#!/Users/maurits/community/plone-coredev/6.1/bin/python3.10

import sys
sys.path[0:0] = [
  '/Users/maurits/community/plone-coredev/6.1/src/plone.recipe.zeoserver/src',
  '/Users/maurits/community/plone-coredev/6.1/src/zc.lockfile/src',
  '/Users/maurits/shared-eggs/cp310/ZopeUndo-6.0-py3.10.egg',
  '/Users/maurits/shared-eggs/cp310/ZODB-6.0.1-py3.10.egg',
  '/Users/maurits/shared-eggs/cp310/ZEO-6.0.0-py3.10.egg',
  '/Users/maurits/shared-eggs/cp310/zdaemon-5.2.1-py3.10.egg',
  '/Users/maurits/shared-eggs/cp310/zc.recipe.egg-3.0.0-py3.10.egg',
  '/Users/maurits/shared-eggs/cp310/zodbpickle-4.1.1-py3.10-macosx-11.0-arm64.egg',
  '/Users/maurits/shared-eggs/cp310/zope.interface-7.2-py3.10-macosx-11.0-arm64.egg',
  '/Users/maurits/shared-eggs/cp310/transaction-5.0-py3.10.egg',
  '/Users/maurits/shared-eggs/cp310/ZConfig-4.2-py3.10.egg',
  '/Users/maurits/shared-eggs/cp310/BTrees-6.1-py3.10-macosx-11.0-arm64.egg',
  '/Users/maurits/shared-eggs/cp310/persistent-6.1-py3.10-macosx-11.0-arm64.egg',
  '/Users/maurits/shared-eggs/cp310/cffi-1.17.1-py3.10-macosx-11.0-arm64.egg',
  '/Users/maurits/shared-eggs/cp310/zope.deferredimport-5.0-py3.10.egg',
  '/Users/maurits/shared-eggs/cp310/pycparser-2.22-py3.10.egg',
  '/Users/maurits/shared-eggs/cp310/zope.proxy-6.1-py3.10-macosx-11.0-arm64.egg',
  '/Users/maurits/community/plone-coredev/6.1/lib/python3.10/site-packages',
  ]

import plone.recipe.zeoserver.ctl

if __name__ == '__main__':
    sys.exit(plone.recipe.zeoserver.ctl.main(
        ["-C", '/Users/maurits/community/plone-coredev/6.1/parts/zeoserver/etc/zeo.conf']
        + sys.argv[1:]))
