#!/bin/sh
SCRIPTNAME="$$1"
shift
ARGS="$$*"
${parts.buildout['executable']}  ${parts.buildout['bin-directory']}/zopepy  -c "from Zope2.Startup.run import make_wsgi_app; make_wsgi_app({}, '${parts.buildout['parts-directory']}/wsgi.py/etc/zope.conf'); import Zope2; app=Zope2.app(); from Testing.makerequest import makerequest; app = makerequest(app); app.REQUEST['PARENTS'] = [app]; from zope.globalrequest import setRequest ;setRequest(app.REQUEST); from AccessControl.SpecialUsers import system as user; from AccessControl.SecurityManagement import newSecurityManager; newSecurityManager(None, user); import sys; sys.argv.pop(); sys.argv.append(r'$$SCRIPTNAME'); [sys.argv.append(x) for x in '$$ARGS'.split()]; exec(compile(open(r'$$SCRIPTNAME').read(), '$$SCRIPTNAME', 'exec'))"
