name: "Shared setup for running full tests"

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.14"
      prepare-command:
        required: false
        type: string
        default: ""
      test-command:
        required: false
        type: string
        default: "make test"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
        PYTHONWARNINGS: ignore
        GIT_CLONE_DEPTH: 1
        CHAMELEON_CACHE: 'chameleon_cache'
        zope_i18n_compile_mo_files: 'true'
        ROBOTSUITE_LOGLEVEL: ERROR
        ROBOTSUITE_PREFIX: ONLYROBOT
    steps:
    - name: OS packages
      run:
        sudo apt-get update && sudo apt-get install -y wv poppler-utils pdftohtml gettext
    - name: locale
      # needed for CMFPlone testUnicodeSplitter test on Ubuntu
      run: |
        sudo locale-gen nl_NL@euro
        sudo update-locale
    - uses: actions/checkout@v4
    - name: Set up Python ${{ inputs.python-version}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version}}
        cache: 'pip'
    - name: Create Chameleon cache dir
      run: |
        mkdir -p "${CHAMELEON_CACHE}"
    - name: Install
      # Run 'make install' twice. Usually the second run still does something.
      run: |
        make install
        make install
    - name: Prepare
      if: ${{ inputs.prepare-command }}
      run: |
        ${{ inputs.prepare-command }}
    - name: Test
      run: |
        ${{ inputs.test-command }}
