name: Run full test suite 3.14

on: push

jobs:
  testproducts:
    name: Products functional 3.14
    uses: ./.github/workflows/full-shared.yml
    with:
      # Note: the ubuntu-latest runners have 4 cpus, so we run tests in parallel.
      test-command: make test TEST_ARGS='-f -j 4 -m Products'

  testploneapp:
    name: plone.app functional 3.14
    uses: ./.github/workflows/full-shared.yml
    with:
      test-command: make test TEST_ARGS='-f -j 4 -m plone.app'

  testother:
    name: other functional 3.14
    uses: ./.github/workflows/full-shared.yml
    with:
      test-command: make test TEST_ARGS='-f -j 4 -m !Products -m !plone.app'

  testrobot:
    name: Robots 3.14
    uses: ./.github/workflows/full-shared.yml
    with:
      prepare-command: make rfbrowser
      # Note: robot tests should not be run in parallel.
      test-command: make test TEST_ARGS='-t ONLYROBOT --all'
