name: make test

on: push

jobs:
  build:
    strategy:
      matrix:
        python-version:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    env:
        PYTHONWARNINGS: ignore
        GIT_CLONE_DEPTH: 1
    steps:
    - name: locale
      # needed for CMFPlone testUnicodeSplitter test
      run: |
        sudo locale-gen nl_NL@euro
        sudo update-locale
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Run make test
      run: |
        make test
