name: make test

on: push

jobs:
  build:
    strategy:
      matrix:
        python-version:
        - "3.13"
        os:
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: locale
      # needed for CMFPlone testUnicodeSplitter test
      run: |
        sudo locale-gen nl_NL@euro
        sudo update-locale
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Run make test
      run: |
        export PYTHONWARNINGS=ignore
        export GIT_CLONE_DEPTH=1
        make test
