name: Run full test suite 3.14

on: push

jobs:
  testproducts:
    name: Products functional 3.14
    uses: ./.github/workflows/full-shared.yml
    with:
      test-command: make test TEST_ARGS='-f --list-tests -m Products'

  testploneapp:
    name: plone.app functional 3.14
    uses: ./.github/workflows/full-shared.yml
    with:
      test-command: make test TEST_ARGS='-f --list-tests -m plone.app'

  testother:
    name: other functional 3.14
    uses: ./.github/workflows/full-shared.yml
    with:
      test-command: make test TEST_ARGS='-f --list-tests -m !Products -m !plone.app'

  testrobot:
    name: Robots 3.14
    uses: ./.github/workflows/full-shared.yml
    with:
      prepare-command: make rfbrowser
      test-command: make test TEST_ARGS='-t ONLYROBOT --all --list-tests'

