name: Running Buildout on 2.7

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster
    steps:
    - uses: actions/checkout@v3
    - name: "Install Python dependencies (pip)"
      uses: "py-actions/py-dependency-install@v3"
      with:
        path: "requirements.txt"
    - name: Cache eggs
      uses: actions/cache@v3
      with:
        path: |
          eggs
        key: eggs-2.7-ubuntu-20.04-${{ hashFiles('versions*.cfg') }}
        restore-keys: |
          eggs-2.7-ubuntu-20.04-
          eggs-2.7-
    - name: Run buildout
      run: |
        buildout buildout:git-clone-depth=1
    - name: Quickly run unit tests without any layers
      # A few tests give problems on the servers, especially
      # plone.testing and testUnicodeSplitter.py.
      # Excluding them does not work.  So let's pick a few packages.
      # This list covers about half the unit tests.
      run: |
        ./bin/test -u -s plone.dexterity -s Products.PluggableAuthService -s Products.GenericSetup -s diazo -s plone.restapi -s plone.resource -s plone.scale -s plone.batching -s plone.protect -s plone.namedfile -s Products.ATContentTypes -s plone.registry
