name: Run full test suite
on:
  push:
    branches:
      - "6.2"
  pull_request:
  workflow_dispatch:
jobs:
  testfunctional:
    name: ${{ matrix.python-version }} ${{ matrix.module }} functional
    strategy:
      matrix:
        python-version:
        - "3.13"
        - "3.14"
        module:
        - Products
        - plone.app
        - "!Products -m !plone.app"
    uses: ./.github/workflows/full-shared.yml
    with:
      python-version: ${{ matrix.python-version }}
      # Note: the ubuntu-latest runners have 4 cpus, so we could run tests in
      # parallel by adding '-j 4' to the TEST_ARGS.  But this can lead to a
      # strange error in zope.i18n.zcml.registerTranslations:
      # struct.error: unpack requires a buffer of 4 bytes
      test-command: make test TEST_ARGS='-f -m ${{ matrix.module }}'

  testrobot:
    name: ${{ matrix.python-version }} ${{ matrix.module }} robots
    strategy:
      matrix:
        python-version:
        - "3.13"
        - "3.14"
        module:
        - Products.CMFPlone
        - "!Products.CMFPlone"
    uses: ./.github/workflows/full-shared.yml
    with:
      python-version: ${{ matrix.python-version }}
      prepare-command: make rfbrowser
      # Note: robot tests should not be run in parallel.
      test-command: make test TEST_ARGS='-t ONLYROBOT --all -m ${{ matrix.module}}'
